// Textos da interface em um lugar só (REPERTORIO 26.8). Sem travessão, sem emoji, frases curtas.
// O P5 começou este arquivo com o fluxo de sessão; o P9 trouxe o resto do ui.js.
// Funções recebem o nome do personagem quando o texto depende dele.
//
// O que NÃO está aqui: o texto fixo do index.html (rótulos e dicas do painel do
// operador), que já mora num arquivo só, e os nomes, personas e falas dos personagens,
// que são dados de cada um em characters.js.

export const T = {
  etapas: {
    atracao: {
      titulo: (nome) => `${nome} está aqui`,
      texto: 'Toque para escolher com quem conversar.',
      acao: 'Escolher personagem',
    },
    consentimento: {
      titulo: 'Posso ouvir você?',
      // Verdade sobre o reconhecimento de voz: no Chrome e no Edge o áudio vai ao serviço do navegador
      // para virar texto. Por isso a frase fala do totem, não de "nada sai daqui".
      texto: 'O microfone só liga quando você aperta o botão vermelho. Nada fica gravado neste totem.',
      camDesligada: 'A câmera está desligada.',
      camLigada: 'A câmera só percebe se tem alguém aqui. A imagem não é gravada nem enviada.',
      acao: 'Usar o microfone',
      alternativa: 'Prefiro escrever',
    },
    conversa: {
      mudarParaVoz: 'Usar o microfone',
    },
    despedida: {
      apagando: 'Apagando a conversa...',
    },
  },
  // Avisos de quiosque: a tela que o público vê quando algo quebra. Sempre com um
  // próximo passo, nunca com termo técnico nem código de erro.
  quiosque: {
    contextoPerdido: {
      titulo: 'Um instante',
      texto: 'A imagem caiu e está voltando sozinha.',
    },
    contextoNaoVoltou: {
      titulo: 'Preciso recomeçar',
      texto: 'A imagem não voltou. Toque no botão para começar de novo.',
      acao: 'Recomeçar',
    },
    travou: {
      titulo: 'Recomeçando',
      texto: 'A tela parou e estou voltando sozinha.',
    },
    desistiu: {
      titulo: 'Preciso de ajuda',
      texto: 'Já tentei voltar sozinha algumas vezes. Chame quem está cuidando do totem.',
      acao: 'Tentar mais uma vez',
    },
    erro: {
      titulo: 'Algo quebrou aqui',
      texto: 'Toque no botão para começar de novo.',
      acao: 'Recomeçar',
    },
  },
  visualizador: {
    barra: 'Controles do visualizador',
    entrar: 'Ver o personagem de perto',
    sair: 'Fechar o visualizador',
    resetar: 'Voltar a câmera ao enquadramento padrão',
    seguir: 'Seguir o personagem',
    telaCheia: 'Tela cheia',
    sairTelaCheia: 'Sair da tela cheia',
    anterior: 'Clipe anterior',
    proximo: 'Próximo clipe',
    tocar: 'Tocar',
    pausar: 'Pausar',
    velocidade: 'Velocidade',
    velocidadeValor: (v) => `${v}x`,
    modo: { um: 'Repetir este clipe', todos: 'Repetir todos em sequência', aleatorio: 'Ordem aleatória' },
    modoRotulo: (m) => `Modo do loop: ${m}`,
    semClipes: 'Nenhum clipe ligado na galeria.',
    semTelaCheia: 'Este navegador não tem tela cheia. A imagem ocupa a janela inteira.',
    galeria: 'Abrir no visualizador',
    atalhos: 'R volta a câmera. F tela cheia. Espaço toca ou pausa. Setas trocam de clipe. T segue o personagem.',
  },
  barra: {
    maisRotulo: 'Mais opções',
    modoRotulo: 'Como conversar',
    // Palavras para quem ainda não lê termos como "guiada": o que cada botão faz. Guiada e Livre ficam só no painel do operador.
    guiada: 'Sugestões',
    livre: 'Perguntar',
    guiadaDica: 'Só perguntas sugeridas',
    livreDica: 'Fale ou escreva',
    menu: {
      verDePerto: 'Ver o personagem de perto',
      legenda: 'O que cada sinal quer dizer',
      centralizar: 'Centralizar o personagem',
      outro: 'Escolher outro personagem',
      terminar: 'Terminar a conversa',
    },
    estados: { idle: 'Pronto', listening: 'Ouvindo', thinking: 'Pensando', speaking: 'Falando', error: 'Problema' },
    legendaTitulo: 'O que cada sinal quer dizer',
    legenda: {
      idle: 'Pronto: pode perguntar.',
      listening: 'Ouvindo: fale e aperte o microfone de novo quando terminar.',
      thinking: 'Pensando: a resposta está a caminho.',
      speaking: 'Falando: a resposta aparece escrita aqui embaixo.',
      error: 'Problema: algo não funcionou. Tente de novo ou chame um adulto.',
    },
  },
  evento: {
    legenda: 'Modo evento',
    dica: 'Para um evento com fila: escolha o modo, limite cada sessão e acompanhe os avisos. O botão de emergência (modo econômico) está na aba Orçamento.',
    modo: 'Modo da conversa',
    modoLivre: 'Conversa livre (Gemini, base e voz)',
    modoGuiada: 'Demonstração guiada (perguntas e respostas prontas, funciona sem internet)',
    guiadaSem: 'Este personagem não tem respostas guiadas aprovadas. Gere com tools/guiada.mjs, aprove e rode npm run conhecimento; sem isso a demonstração guiada mostra só as sugestões de sempre.',
    guiadaTem: (n) => `${n} respostas guiadas aprovadas para este personagem.`,
    turnos: 'Perguntas por sessão (0 = sem limite)',
    minutos: 'Minutos por sessão (0 = sem limite)',
    fila: 'Fila',
    filaMais: 'Mais uma pessoa na fila',
    filaMenos: 'Chamar a próxima pessoa',
    filaTexto: (n) => (n === 1 ? '1 pessoa na fila' : `${n} pessoas na fila`),
    pacote: 'Gerar áudio das respostas guiadas',
    pacoteDica: 'Sintetiza com a voz Kokoro e guarda em disco, para tocar mesmo com o servidor de voz fora do ar. Só voz gratuita: com voz paga o app recusa, porque isso gastaria crédito.',
    pacoteProgresso: (n, total) => `Gerando ${n} de ${total}`,
    pacotePronto: (n) => `${n} respostas guardadas em disco.`,
    pacotePaga: 'A voz atual é paga. Troque para Kokoro nas configurações de voz antes de gerar o pacote.',
    pacoteSem: 'Nenhuma resposta guiada aprovada.',
    avisos: 'Avisos do evento',
    semAvisos: 'nenhum',
    aviso: {
      reserva: 'Modelo principal falhou: respondendo com o modelo reserva.',
      pronta: 'Gemini indisponível: respondendo com a resposta pronta da base.',
      lento: 'Gemini lento demais: passando para o plano de reserva.',
      semRede: 'Sem internet: demonstração guiada com respostas prontas.',
      redeVoltou: 'A internet voltou.',
      limiteTurnos: 'Sessão encerrada: limite de perguntas.',
      limiteTempo: 'Sessão encerrada: limite de tempo.',
      chaveRecusada: 'O Gemini recusou a chave: confira a chave na aba Orçamento ou no proxy.',
      modeloNaoExiste: (m) => `O modelo "${m}" não existe para esta chave (HTTP 404): troque o nome do modelo na engrenagem.`,
    },
    guiadaResposta: 'Resposta pronta, sem chamar o Gemini.',
  },
  orcamento: {
    legenda: 'Orçamento e teto de gasto',
    dica: 'O gasto de texto (Gemini) e de voz paga conta num teto só, acumulado de um dia para o outro. Aos 80% o operador é avisado; no teto, o app passa sozinho ao plano gratuito (voz Kokoro e respostas prontas da base) e avisa. O preço vem da tabela do diagnóstico, que pode ser editada.',
    teto: 'Teto de gasto (R$)',
    reserva: 'Modelo reserva, mais barato',
    reservaDica: 'Se o modelo principal der erro de cota ou ficar fora do ar, o app tenta este uma vez antes de cair para a resposta pronta.',
    economico: 'Modo econômico: só voz Kokoro e respostas prontas, sem chamar o Gemini',
    proxy: 'Endereço do proxy local (opcional)',
    proxyDica: 'Com o proxy (npm run proxy) a chave do Gemini fica no servidor, que também conta o gasto e aplica o teto. Preencha, por exemplo, http://127.0.0.1:8890 e a chave deixa de ser usada neste navegador para o texto. Não vale para a voz Gemini TTS.',
    diagnostico: 'Orçamento',
    diagnosticoValor: (gasto, teto, pct) => `R$ ${gasto} de R$ ${teto} (${pct}%)`,
    diagnosticoSemTeto: (gasto) => `R$ ${gasto}, sem teto definido`,
    aviso: (pct) => `Atenção: o gasto chegou a ${pct}% do teto.`,
    estourou: 'O teto de gasto acabou. O app está no modo econômico: só respostas prontas e voz Kokoro.',
    semBase: 'Agora só consigo responder o que já está pronto. Chame um adulto para continuar a conversa.',
    seloManual: 'Modo econômico ligado à mão. Toque para desligar.',
    seloTeto: (gasto, teto) => `Modo econômico: teto atingido (R$ ${gasto} de R$ ${teto}). Toque para ver.`,
    estadoManual: 'O modo econômico está LIGADO À MÃO (caixa abaixo). Enquanto estiver marcado, perguntas livres não chamam o Gemini e só saem respostas prontas da base.',
    estadoTeto: (gasto, teto) => `O modo econômico está LIGADO porque o gasto acumulado (R$ ${gasto}) chegou ao teto (R$ ${teto}). Perguntas livres só saem como respostas prontas da base. Aumente o teto ou zere o gasto acumulado para voltar ao normal.`,
    estadoNormal: (gasto, teto) => `Modo econômico desligado. Gasto acumulado: R$ ${gasto}${teto > 0 ? ` de R$ ${teto}` : ', sem teto'}.`,
    zerar: 'Zerar o gasto acumulado',
    avisoModo: (motivo) => `Modo econômico ativo (${motivo}): a pergunta livre não foi ao Gemini.`,
    motivoManual: 'ligado à mão na aba Orçamento',
    motivoTeto: (gasto, teto) => `teto atingido, R$ ${gasto} de R$ ${teto}`,
    reservaUsada: 'O modelo principal falhou e a resposta veio do modelo reserva.',
    prontaDoRag: 'Resposta pronta da base, sem chamar o Gemini.',
  },
  maosLivres: {
    rotulo: 'Voz mãos-livres (experimental)',
    dica: 'O microfone fica aberto durante a conversa e o app percebe sozinho quando a pessoa começa e termina de falar. Falar por cima do personagem interrompe ele. Usa um detector de voz que já vem junto (13 MB) e o Whisper no navegador: a primeira vez baixa o modelo de transcrição. Nada é gravado nem enviado. Com fone de ouvido funciona melhor; sem ele, o som do alto-falante pode ser entendido como fala. Vem desligado, e o botão de apertar para falar continua valendo.',
    pronto: 'Pode falar: estou ouvindo.',
    precisaMicrofone: 'Para usar a voz mãos-livres, aceite o microfone no começo da conversa.',
  },
  rag: {
    avisoSemBase: (nome) => `A base de conhecimento de ${nome} não está preparada: abra a engrenagem, aba Personagem, Base de conhecimento, e toque em Preparar a base. Enquanto isso, perguntas do assunto dela não vão ao Gemini.`,
    eDaLuma: 'Essa pergunta é para a Luma. Chame a Luma para conversar sobre a UEMA e o CTIC.',
    legenda: 'Base de conhecimento',
    dica: 'Documentos em knowledge/<personagem>/ com "fonte:" e "licenca:" no cabeçalho. O personagem responde só com o que está neles e diz que não sabe quando a base não cobre. A primeira preparação baixa um modelo de 118 MB para este navegador (Hugging Face, Xenova/multilingual-e5-small) e depois guarda. Nada do que a criança pergunta sai deste computador para essa busca.',
    semDocumentos: 'Este personagem não tem documentos. Ele responde como sempre.',
    estado: (docs, indexados) => `${indexados} de ${docs} documentos indexados`,
    preparar: 'Preparar a base',
    preparando: (n, total) => `Indexando ${n} de ${total}`,
    baixandoModelo: (pct) => `Baixando o modelo: ${pct}%`,
    pronto: 'Base pronta.',
    recusado: (arq, erros) => `Recusado: ${arq} (${erros.join('; ')}).`,
    falhou: (motivo) => `Não deu certo: ${motivo}`,
    apagar: 'Apagar o índice',
    limiar: 'Limiar de confiança',
    limiarDica: 'Abaixo dele o personagem diz que não sabe. Ainda NÃO calibrado: use "Testar uma pergunta" com perguntas dentro e fora da base e ajuste.',
    testar: 'Testar uma pergunta',
    testarBotao: 'Testar',
    testarSemBase: 'Prepare a base antes de testar.',
    testarResultado: (melhor, confiante) => `Melhor semelhança: ${melhor}. ${confiante ? 'Acima do limiar: responderia com a base.' : 'Abaixo do limiar: diria que não sabe.'}`,
    naoSei: (nome) => `Não encontrei isso na minha base. Você pode perguntar de outro jeito?`,
    naoSeiTema: (nome) => `Não encontrei isso na minha base. Para esse assunto, o melhor é consultar o portal oficial. Posso ajudar com outra pergunta?`,
    fontes: (lista) => `Fontes: ${lista.join('; ')}`,
  },
  console: {
    abas: { cena: 'Cena', personagem: 'Personagem', voz: 'Voz', animacoes: 'Animações', orcamento: 'Orçamento', evento: 'Evento', armazenamento: 'Armazenamento', sessao: 'Sessão' },
    rotuloAbas: 'Seções das configurações',
    cenaLegenda: 'Cena do personagem',
    cenaDica: 'Vale para o personagem escolhido em "Personagem". Se for o que está em cena, a mudança aparece na hora. Fica guardada só neste navegador.',
    luz: 'Luz',
    luzAmbiente: 'Ambiente', luzPrincipal: 'Principal', luzPreenchimento: 'Preenchimento frio', luzRecorte: 'Recorte quente',
    fundo: 'Fundo',
    fundoTopo: 'Cor de cima', fundoBase: 'Cor de baixo',
    fundoAviso: (r) => `Contraste do texto com este fundo: ${r}:1. Abaixo de 4,5:1 a letra fica difícil de ler; a mudança não foi aplicada.`,
    enquadramento: 'Enquadramento',
    distancia: 'Distância da câmera (metros)', altura: 'Altura do foco',
    restaurarCena: 'Restaurar a cena deste personagem',
    painelEncaixado: 'Painel encaixado: a cena fica visível ao lado.',
  },
  totem: {
    rotulo: 'Modo totem: tela cheia e saída escondida',
    dica: 'Entra em tela cheia no primeiro toque, esconde a engrenagem e bloqueia o menu do botão direito. Para voltar aqui: segure o canto superior direito por 3 segundos ou aperte Ctrl+Shift+O.',
    ponto: 'Área do operador: segure para abrir as configurações',
  },
  armazenamento: {
    legenda: 'Armazenamento e uso offline',
    dica: 'O app guarda as bibliotecas, os personagens e as animações neste navegador para abrir sem internet depois da primeira visita. Chaves de API nunca são guardadas aqui.',
    uso: 'Espaço usado',
    usoValor: (usado, cota) => `${usado} de ${cota}`,
    permanente: 'Armazenamento permanente',
    permanenteSim: 'sim, o navegador não apaga sozinho',
    permanenteNao: 'não, o navegador pode apagar se faltar espaço',
    pedirPermanente: 'Pedir armazenamento permanente',
    pediuNegado: 'O navegador não concedeu. Instalar o app ou usar o site com frequência ajuda.',
    shell: 'Página e códigos do app',
    binarios: 'Personagens, animações e imagens',
    bibliotecas: 'Bibliotecas externas (cache)',
    audio: 'Áudio das frases fixas',
    apagarAudio: 'Apagar áudio das frases',
    semDado: 'sem dado',
    personagens: 'Pronto para usar offline',
    pronto: 'pronto offline',
    naoPronto: 'ainda não',
    baixar: 'Baixar para offline',
    baixando: (n, total) => `Baixando ${n} de ${total}`,
    baixou: 'Pronto.',
    falhou: (motivo) => `Não deu certo: ${motivo}`,
    apagarBinarios: 'Apagar personagens e animações',
    apagarBibliotecas: 'Apagar bibliotecas',
    apagarTudo: 'Apagar tudo',
    apagou: (n) => `Apagado (${n} grupos).`,
    semServiceWorker: 'Este navegador não permite uso offline aqui (precisa de https ou localhost). O app funciona, mas só com internet.',
    emDebug: 'Uso offline desligado com ?debug.',
    atualizacao: 'Atualização',
    atualizado: 'Esta é a versão mais nova.',
    nova: 'Há uma versão nova pronta. Atualizar reinicia a página; faça isso entre uma conversa e outra.',
    atualizar: 'Atualizar agora',
  },
  titulos: {
    atracao: 'Professores 3D: vitrine de personagens',
    selecao: 'Professores 3D: escolha de personagem',
    consentimento: (nome) => `Conversa com ${nome}: permissões`,
    conversa: (nome) => `Conversa com ${nome}`,
    visualizador: (nome) => `Visualizador de ${nome}`,
  },
  vitrine: {
    regiao: 'Vitrine de personagens',
    dica: 'Toque na tela para escolher quem vai conversar',
    cta: 'Toque para escolher',
  },
  selecao: {
    regiao: 'Escolha de personagem',
    comoFunciona: 'Como funciona',
    comoTitulo: 'Como funciona',
    comoPassos: ['Escolha quem vai conversar com você.', 'Aperte o botão grande para começar.', 'Fale ou escreva a sua pergunta.'],
    fechar: 'Fechar',
    conversar: (nome) => `Conversar com ${nome}`,
    ouvirVoz: 'Ouvir voz',
    semAudio: 'Ainda não tem áudio gravado',
    preparandoAudio: 'Preparando o áudio...',
    semAudioSistema: 'A voz do sistema não guarda áudio',
    semAudioPaga: 'Voz paga não pré-grava sozinha; só toca áudio já guardado',
    semAudioServidor: 'O servidor de voz está fora do ar',
    emBreve: 'Em breve',
    emBreveNome: (nome) => `${nome}, em breve`,
    ficcao: 'Traços inventados para o jogo, não são dados reais.',
    perfilAria: (rotulo, valor) => `${rotulo}: ${valor} de 5`,
    contador: (i, n) => `${i} de ${n}`,
    anterior: 'Personagem anterior',
    proximo: 'Personagem seguinte',
    roleta: 'Personagens',
  },
  quadro: {
    naoConferido: 'Número que não veio da calculadora nem do enunciado',
  },
  volume: {
    mudo: 'sem som',
    mudar: 'Desligar o som',
    religar: 'Ligar o som',
  },
  carga: {
    baixando: (nome) => `Chamando ${nome}`,
    movimentos: 'Preparando os movimentos',
  },
  licenca: {
    bloqueado: (nome) => `A licença do avatar de ${nome} não permite este uso.`,
    nenhum: 'Nenhum avatar carregado ainda.',
    decisao: { permitido: 'permitido', conferir: 'permitido, conferir', bloqueado: 'bloqueado' },
  },
  creditos: {
    titulo: 'Créditos',
    fechar: 'Fechar',
    erro: 'Não consegui ler os arquivos de créditos.',
    terceiros: 'Código de terceiros',
    terceirosLista: 'three.js (MIT), @pixiv/three-vrm e o exemplo de Mixamo do three-vrm (MIT, pixiv Inc.), MediaPipe (Apache 2.0), Kokoro (Apache 2.0).',
  },
  // Linha de estado embaixo da bolha de fala.
  estado: {
    idle: 'Aperte o microfone e fale!',
    listening: 'Estou ouvindo... aperte de novo quando terminar',
    thinking: 'Pensando...',
    speaking: 'Falando...',
    error: 'Algo deu errado.',
    tentarDeNovo: 'Tentar de novo',
    preparandoOuvido: 'Preparando o ouvido...',
    preparandoOuvidoPct: (pct) => `Preparando o ouvido... ${pct}%`,
    semChave: 'Um adulto precisa colocar a chave do Gemini na engrenagem.',
    pronto: 'Tudo pronto!',
    faltaChave: 'Falta a chave do Gemini.',
    voce: (texto) => `Você: ${texto}`,
  },
  avatar: {
    falar: (nome) => `Falar com ${nome}`,
    ausente: (nome) => `Falta o arquivo do avatar de ${nome}.`,
    naoAbriu: (nome) => `O arquivo do avatar de ${nome} não abriu. Confira se é um .vrm válido.`,
    nenhum: 'Nenhum avatar encontrado.',
    // O que a criança lê quando o arquivo some. O detalhe técnico fica num bloco para o adulto.
    criancaTitulo: 'Não consegui chamar este personagem.',
    criancaAjuda: 'Chame um adulto para ajudar.',
    paraOAdulto: 'Para o adulto',
  },
  vozGemini: {
    semChave: 'Falta a chave do Gemini para a voz. Usando outra voz.',
    teto: 'O teto de caracteres do Gemini TTS acabou por hoje. Usando outra voz.',
    uso: (n, chars, teto, reais) => `Hoje: ${n} falas, ${chars} caracteres${teto ? ` de ${teto}` : ''}, R$ ${reais}.`,
  },
  voz: {
    selo: {
      verificando: 'Voz: verificando',
      edge: 'Voz: Edge Natural',
      sistema: 'Voz do sistema',
      navegador: 'Voz: Kokoro no navegador',
      kokoro: 'Voz: Kokoro',
      gemini: 'Voz: Gemini',
      reserva: (nome) => `${nome} (reserva)`,
      servidorFora: 'Voz do sistema: servidor Kokoro fora do ar',
    },
    servidorOk: (detalhe) => `Servidor respondendo (${detalhe}).`,
    servidorRuim: (detalhe) => `Servidor ${detalhe}.`,
    verificando: 'Verificando o servidor...',
    automatica: 'Automática por personagem',
    baixandoModelo: (pct) => `Baixando o modelo Kokoro para o navegador... ${pct}%`,
    navegadorFalhou: 'O Kokoro no navegador não carregou. Veja o console.',
    teste: (nome) => `Oi! Eu sou ${nome}. Esta é a minha voz.`,
    testeIngles: (nome) => `Hi, I am ${nome}. This is the English voice.`,
  },
  resposta: {
    vazia: 'Hmm, não consegui responder isso. Vamos tentar outra pergunta?',
    chaveRecusada: 'A chave da API não foi aceita. Confira na engrenagem.',
    recusado: (motivo) => `O Gemini recusou o pedido (400): ${motivo}`,
    muitasPerguntas: 'Muitas perguntas de uma vez. Espere um pouquinho!',
    modeloNaoExiste: (m) => `Não achei o modelo "${m}" no Gemini (404). Um adulto precisa trocar o nome do modelo na engrenagem.`,
    erroHttp: (status) => `Ops, deu erro (${status}). Tente de novo!`,
    semInternet: 'Não consegui falar com o Gemini. Confira a internet e tente de novo!',
  },
  photobooth: {
    rotulo: 'Estúdio de fotos do personagem',
    faixa: 'Animações',
    mais: 'Mais animações',
    abas: { animacoes: 'Animações', expressoes: 'Expressões', rastreamento: 'Rastreamento', fundo: 'Fundo e foto' },
    clipeAtual: 'Clipe atual', repeticao: 'Repetição', um: 'Um', todos: 'Todos', aleatorio: 'Aleatório', velocidade: 'Velocidade',
    pausar: 'Pausar', tocar: 'Tocar', novo: 'Novo',
    operador: 'Só operador', enviarVrma: 'Enviar movimento (.vrma)',
    enviarDica: 'O arquivo é validado e fica marcado como temporário até você aprovar.',
    expressao: { happy: 'Feliz', surprised: 'Surpreso', sad: 'Triste', relaxed: 'Calmo', angry: 'Bravo', neutral: 'Normal' },
    zerar: 'Normal',
    olharCamera: 'Olhar para a câmera',
    imitar: 'Imitar meus movimentos',
    imitarDica: 'Liga a câmera. Fique parado por um instante para calibrar. Nada é gravado.',
    fundo: 'Fundo',
    foto: 'Foto', video: 'Vídeo',
    desligadoPublico: 'Foto e vídeo ficam desligados no modo público.',
    nomes: { idle: 'Em pé', aceno: 'Aceno', 'mostrar-corpo': 'Apresentação', 'sinal-paz': 'Sinal de paz', giro: 'Giro', 'pose-modelo': 'Pose de modelo', agachar: 'Agachar', 'dedo-arma': 'Apontar', 'cumprimento-agachado': 'Cumprimento', 'aceno-ciclo': 'Balançar a mão', 'fala-leve': 'Falando (calma)', 'fala-base': 'Falando', 'fala-media': 'Falando (médio)', 'fala-mao-esq': 'Falando (mão)', 'fala-mao-dir': 'Falando (outra mão)', assentir: 'Sim com a cabeça', pensar: 'Pensando', aplauso: 'Palmas' },
  },
  captura: {
    exprDica: 'Valem para o personagem em cena e sobrescrevem as expressões do clipe; a boca falando vem antes de tudo. Só aparecem as expressões que o modelo realmente tem.',
    zerar: 'Zerar expressões',
    olhar: 'Olhar',
    olharAuto: 'Automático (segue o rosto da câmera ou faz sacadas)',
    olharCamera: 'Olhar para a câmera',
    olharDirecao: 'Escolher a direção',
    yaw: 'Direção do olhar: esquerda e direita',
    pitch: 'Direção do olhar: para baixo e para cima',
    dica: 'Foto e vídeo capturam só o personagem (nunca a imagem da webcam nem a interface) e salvam neste computador, sem envio. Só funcionam se a licença do modelo e a do clipe em uso permitirem, e mostram o crédito exigido.',
    liberar: 'Permitir foto e vídeo (só o operador; fica desligado no modo totem)',
    proporcao: 'Proporção',
    fundo: 'Fundo',
    fundoTransparente: 'Transparente',
    fundoBranco: 'Branco',
    fundoPaleta: 'Cor do personagem',
    moldura: 'Moldura visível',
    credito: 'Escrever o crédito na imagem',
    duracao: 'Duração máxima do vídeo (segundos)',
    confirmar: 'Conferi as condições de licença acima e confirmo o uso',
    tirarFoto: 'Tirar foto (contagem de 3 segundos)',
    gravarVideo: 'Gravar vídeo',
    pararVideo: 'Parar e salvar',
    modoPublico: 'Desligado no modo totem.',
    desligada: 'Desligado: marque "Permitir foto e vídeo".',
    bloqueado: (m) => `Bloqueado pela licença: ${m}.`,
    conferir: (m) => `Falta conferir: ${m}.`,
    creditoExigido: (c) => `Crédito: ${c}.`,
    contagem: (n) => `Foto em ${n}...`,
    gravando: (r) => `Gravando: ${r} s restantes.`,
    fotoSalva: 'Foto salva neste computador.',
    videoSalvo: 'Vídeo salvo neste computador.',
    erro: (m) => `Não consegui: ${m}`,
  },
  corpo: {
    legenda: 'Rastreamento do corpo',
    privacidade: 'A imagem da câmera nunca sai deste computador: nada é gravado, salvo ou enviado. Só a posição do corpo vira números usados na hora. Começa desligado e só liga quando você pedir.',
    imitar: 'Imitar meus movimentos',
    imitarDica: 'Liga a câmera. Fique em pose neutra e parado por um instante.',
    bracos: 'Braços',
    tronco: 'Tronco',
    maos: 'Mãos e dedos',
    movimento: 'Movimento do corpo (andar para os lados e para a frente)',
    gestos: 'Gestos: acenar e joinha',
    espelho: 'Espelho (a sua mão direita move o braço que aparece do lado direito da tela)',
    qualidade: 'Qualidade',
    leve: 'Leve',
    equilibrada: 'Equilibrada',
    recalibrar: 'Recalibrar',
    gravar: 'Gravar números da sessão',
    pararGravar: 'Parar e baixar',
    repetir: 'Repetir uma sessão gravada',
    estados: {
      desligado: 'Desligado.',
      ligando: 'Ligando a câmera e carregando os modelos...',
      calibrando: 'Fique em pose neutra, parado.',
      procurando: 'Mostre o corpo para a câmera: ombros e braços.',
      calibrandoPct: (n) => `Calibrando, fique parado: ${n}%`,
      calibrandoMexeu: 'Você se mexeu. Fique parado um instante para calibrar.',
      rastreando: 'Rastreando.',
      perdeu: 'Perdi o corpo: volte para dentro da imagem.',
      erro: (m) => `Não liguei: ${m}.`,
    },
    stats: (s) => `${s.fps} quadros por segundo, ${s.latenciaMs ?? '?'} ms de atraso, ${s.delegado || '?'}, modelo ${s.modelo || '?'}.`,
    confianca: (c) => `Confiança: braço esquerdo da tela ${Math.round((c.bracoEsq ?? 0) * 100)}%, direito ${Math.round((c.bracoDir ?? 0) * 100)}%, tronco ${Math.round((c.tronco ?? 0) * 100)}%. Abaixo de 50% a parte volta para a animação: mostre o cotovelo e a mão para a câmera.`,
    sessaoInvalida: 'Esse arquivo não é uma sessão de números válida.',
  },
  camera: {
    ligar: 'Ligar a câmera',
    desligar: 'Desligar a câmera',
    ligando: 'Ligando a câmera...',
    ligada: (delegado) => `Câmera ligada (${delegado}).`,
    desligada: 'Câmera desligada.',
    erro: (motivo) => `A câmera não ligou: ${motivo}.`,
  },
  galeria: {
    semCatalogo: 'Catálogo de animações não carregou.',
    naoAbriu: (arquivo) => `Não abriu ${arquivo}. Confira se o arquivo está na pasta.`,
    pausar: 'Pausar',
    continuar: 'Continuar',
    meta: (dur, loop, intensidade) => `${dur} | ${loop ? 'laço' : 'uma vez'} | intensidade ${intensidade}`,
    lacunas: (ids) => `Faltam clipes para: ${ids}.`,
    soNaGaleria: 'Só na galeria',
  },
  envio: {
    escolhaArquivo: 'Escolha um arquivo .fbx (Mixamo) ou .vrma.',
    tipoInvalido: 'Só aceito .fbx do Mixamo ou .vrma.',
    espereCarregar: 'Espere o personagem carregar.',
    convertendo: 'Convertendo...',
    fbxNaoAbriu: 'Não consegui ler esse FBX. Baixe do Mixamo em FBX, "Without Skin".',
    vrmaNaoAbriu: 'Esse .vrma não abriu.',
    semEspaco: 'Sem espaço no navegador para guardar o arquivo.',
    falhou: 'O envio falhou. Veja o console.',
    naoApagou: 'Não consegui apagar. Veja o console.',
    pronto: (dur, uso) => `Pronto: ${dur}${uso ? `, usado como "${uso}"` : ''}. `,
    comAvisos: (avisos) => `Atenção: ${avisos}.`,
    semAvisos: 'Corpo parado e começo e fim parecidos.',
    olheAPrevia: ' Olhe a prévia: a mão na frente do rosto só se vê tocando.',
    licencaFbx: 'Mixamo (termos da Adobe); não redistribuir',
    licencaVrma: 'conferir a licença do arquivo enviado',
  },
  // Painel do operador. O público nunca vê nada daqui.
  diagnostico: {
    versao: 'Versão',
    emPe: 'Em pé há',
    fps: 'Quadros por segundo',
    medindo: 'medindo',
    imagem: 'Imagem',
    imagemPerdida: 'contexto perdido',
    imagemOk: 'normal',
    memoria: 'Memória',
    memoriaValor: (usada, limite) => `${usada} MB de ${limite} MB`,
    semMemoria: 'o navegador não informa',
    gpu: 'Na placa de vídeo',
    gpuValor: (g, t) => `${g} geometrias, ${t} texturas`,
    semDados: 'sem dados',
    respostaGemini: 'Resposta do Gemini',
    ateFala: 'Até a primeira fala',
    semMedida: 'sem medida ainda',
    qualidade: 'Qualidade da imagem',
    qualidadeValor: (pr, auto) => `pixel ratio ${pr}${auto ? ', ajuste automático por FPS' : ', ajuste automático desligado'}`,
    vozAgora: 'Voz do personagem',
    vozAgoraValor: (nome, id, motor) => `${nome}: ${id} no motor ${motor}`,
    vozGemini: 'Voz Gemini hoje',
    vozGeminiValor: (n, chars, reais, mediana) => `${n} falas, ${chars} caracteres, R$ ${reais}${mediana ? `, mediana ${mediana} ms` : ''}`,
    vozGeminiNenhuma: 'sem uso hoje',
    ms: (v, n) => (n ? `${v} ms (mediana de ${n})` : `${v} ms`),
    respostasHoje: 'Respostas hoje',
    respostasValor: (dia, sessao) => `${dia} (${sessao} nesta sessão)`,
    tokensHoje: 'Tokens hoje',
    tokensValor: (entrada, saida) => `${entrada} de entrada, ${saida} de saída`,
    transcricao: 'Fim da fala até o texto',
    orcamento: 'Orçamento (teto)',
    gastoHoje: 'Gasto hoje',
    gastoValor: (reais) => `R$ ${reais}`,
    gastoSemPreco: (reais, modelos) => `R$ ${reais}, sem preço para ${modelos}`,
    projecao: 'Projeção de 5.000 respostas',
    projecaoValor: (reais, modelo, base) => `R$ ${reais} no ${modelo} (${base})`,
    projecaoMedida: (n) => `média de ${n} respostas medidas`,
    projecaoPremissa: 'premissa de 2.000 tokens de entrada e 200 de saída, ainda não medida',
    projecaoSemPreco: (modelo) => `sem preço para ${modelo}`,
    recargas: 'Recargas automáticas',
    erros: 'Erros',
    semErros: 'nenhum',
    errosValor: (n, hora) => `${n}, último às ${hora}`,
    fonte: (fonte) => `Preços: ${fonte}. Sem preço do modelo na tabela, o gasto aparece só em tokens.`,
    semPerdaDeContexto: 'Este navegador não deixa derrubar o contexto de propósito (falta WEBGL_lose_context).',
    servicos: {
      gemini: (modelo) => `chave configurada, modelo ${modelo}`,
      semChave: 'sem chave',
      servidorOk: ' (servidor respondendo)',
      servidorRuim: (detalhe) => ` (servidor ${detalhe})`,
      escolhendo: 'escolhendo',
      ouvindo: 'ouvindo agora',
      ouvidoPronto: 'pronto',
      camLigada: 'ligada',
      camDesligada: 'desligada',
      avatar: (nome, licenca) => `${nome} carregado${licenca ? `, licença ${licenca}` : ''}`,
      semAvatar: 'sem avatar',
    },
  },
};
