// Textos da interface em um lugar só (REPERTORIO 26.8). Sem travessão, sem emoji, frases curtas.
// O P5 começou este arquivo com o fluxo de sessão; o P9 trouxe o resto do ui.js.
// Funções recebem o nome do personagem quando o texto depende dele.
//
// O que NÃO está aqui: o texto fixo do index.html (rótulos e dicas do painel do
// operador), que já mora num arquivo só, e os nomes, personas e falas dos personagens,
// que são dados de cada um em characters.js.

export const T = {
  etapas: {
    atracao: {
      titulo: (nome) => `${nome} está aqui`,
      texto: 'Toque para começar uma conversa.',
      acao: 'Começar',
    },
    consentimento: {
      titulo: 'Posso ouvir você?',
      // Verdade sobre o reconhecimento de voz: no Chrome e no Edge o áudio vai ao serviço do navegador
      // para virar texto. Por isso a frase fala do totem, não de "nada sai daqui".
      texto: 'O microfone só liga quando você aperta o botão vermelho. Nada fica gravado neste totem.',
      camDesligada: 'A câmera está desligada.',
      camLigada: 'A câmera só percebe se tem alguém aqui. A imagem não é gravada nem enviada.',
      acao: 'Usar o microfone',
      alternativa: 'Prefiro escrever',
    },
    conversa: {
      mudarParaVoz: 'Usar o microfone',
    },
    despedida: {
      apagando: 'Apagando a conversa...',
    },
  },
  // Avisos de quiosque: a tela que o público vê quando algo quebra. Sempre com um
  // próximo passo, nunca com termo técnico nem código de erro.
  quiosque: {
    contextoPerdido: {
      titulo: 'Um instante',
      texto: 'A imagem caiu e está voltando sozinha.',
    },
    contextoNaoVoltou: {
      titulo: 'Preciso recomeçar',
      texto: 'A imagem não voltou. Toque no botão para começar de novo.',
      acao: 'Recomeçar',
    },
    travou: {
      titulo: 'Recomeçando',
      texto: 'A tela parou e estou voltando sozinha.',
    },
    desistiu: {
      titulo: 'Preciso de ajuda',
      texto: 'Já tentei voltar sozinha algumas vezes. Chame quem está cuidando do totem.',
      acao: 'Tentar mais uma vez',
    },
    erro: {
      titulo: 'Algo quebrou aqui',
      texto: 'Toque no botão para começar de novo.',
      acao: 'Recomeçar',
    },
  },
  volume: {
    mudo: 'sem som',
    mudar: 'Desligar o som',
    religar: 'Ligar o som',
  },
  carga: {
    baixando: (nome) => `Chamando ${nome}`,
    movimentos: 'Preparando os movimentos',
  },
  licenca: {
    bloqueado: (nome) => `A licença do avatar de ${nome} não permite este uso.`,
    nenhum: 'Nenhum avatar carregado ainda.',
    decisao: { permitido: 'permitido', conferir: 'permitido, conferir', bloqueado: 'bloqueado' },
  },
  creditos: {
    titulo: 'Créditos',
    fechar: 'Fechar',
    erro: 'Não consegui ler os arquivos de créditos.',
    terceiros: 'Código de terceiros',
    terceirosLista: 'three.js (MIT), @pixiv/three-vrm e o exemplo de Mixamo do three-vrm (MIT, pixiv Inc.), MediaPipe (Apache 2.0), Kokoro (Apache 2.0).',
  },
  // Linha de estado embaixo da bolha de fala.
  estado: {
    idle: 'Aperte o microfone e fale!',
    listening: 'Estou ouvindo... aperte de novo quando terminar',
    thinking: 'Pensando...',
    speaking: 'Falando...',
    error: 'Algo deu errado.',
    preparandoOuvido: 'Preparando o ouvido...',
    preparandoOuvidoPct: (pct) => `Preparando o ouvido... ${pct}%`,
    semChave: 'Um adulto precisa colocar a chave do Gemini na engrenagem.',
    pronto: 'Tudo pronto!',
    faltaChave: 'Falta a chave do Gemini.',
    voce: (texto) => `Você: ${texto}`,
  },
  avatar: {
    falar: (nome) => `Falar com ${nome}`,
    ausente: (nome) => `Falta o arquivo do avatar de ${nome}.`,
    naoAbriu: (nome) => `O arquivo do avatar de ${nome} não abriu. Confira se é um .vrm válido.`,
    nenhum: 'Nenhum avatar encontrado.',
  },
  voz: {
    selo: {
      verificando: 'Voz: verificando',
      edge: 'Voz: Edge Natural',
      sistema: 'Voz do sistema',
      navegador: 'Voz: Kokoro no navegador',
      kokoro: 'Voz: Kokoro',
      servidorFora: 'Voz do sistema: servidor Kokoro fora do ar',
    },
    servidorOk: (detalhe) => `Servidor respondendo (${detalhe}).`,
    servidorRuim: (detalhe) => `Servidor ${detalhe}.`,
    verificando: 'Verificando o servidor...',
    automatica: 'Automática por personagem',
    baixandoModelo: (pct) => `Baixando o modelo Kokoro para o navegador... ${pct}%`,
    navegadorFalhou: 'O Kokoro no navegador não carregou. Veja o console.',
    teste: (nome) => `Oi! Eu sou ${nome}. Esta é a minha voz.`,
    testeIngles: (nome) => `Hi, I am ${nome}. This is the English voice.`,
  },
  resposta: {
    vazia: 'Hmm, não consegui responder isso. Vamos tentar outra pergunta?',
    chaveRecusada: 'A chave da API não foi aceita. Confira na engrenagem.',
    recusado: (motivo) => `O Gemini recusou o pedido (400): ${motivo}`,
    muitasPerguntas: 'Muitas perguntas de uma vez. Espere um pouquinho!',
    erroHttp: (status) => `Ops, deu erro (${status}). Tente de novo!`,
    semInternet: 'Não consegui falar com o Gemini. Confira a internet e tente de novo!',
  },
  camera: {
    ligar: 'Ligar a câmera',
    desligar: 'Desligar a câmera',
    ligando: 'Ligando a câmera...',
    ligada: (delegado) => `Câmera ligada (${delegado}).`,
    desligada: 'Câmera desligada.',
    erro: (motivo) => `A câmera não ligou: ${motivo}.`,
  },
  galeria: {
    semCatalogo: 'Catálogo de animações não carregou.',
    naoAbriu: (arquivo) => `Não abriu ${arquivo}. Confira se o arquivo está na pasta.`,
    pausar: 'Pausar',
    continuar: 'Continuar',
    meta: (dur, loop, intensidade) => `${dur} | ${loop ? 'laço' : 'uma vez'} | intensidade ${intensidade}`,
    lacunas: (ids) => `Faltam clipes para: ${ids}.`,
    soNaGaleria: 'Só na galeria',
  },
  envio: {
    escolhaArquivo: 'Escolha um arquivo .fbx (Mixamo) ou .vrma.',
    tipoInvalido: 'Só aceito .fbx do Mixamo ou .vrma.',
    espereCarregar: 'Espere o personagem carregar.',
    convertendo: 'Convertendo...',
    fbxNaoAbriu: 'Não consegui ler esse FBX. Baixe do Mixamo em FBX, "Without Skin".',
    vrmaNaoAbriu: 'Esse .vrma não abriu.',
    semEspaco: 'Sem espaço no navegador para guardar o arquivo.',
    falhou: 'O envio falhou. Veja o console.',
    naoApagou: 'Não consegui apagar. Veja o console.',
    pronto: (dur, uso) => `Pronto: ${dur}${uso ? `, usado como "${uso}"` : ''}. `,
    comAvisos: (avisos) => `Atenção: ${avisos}.`,
    semAvisos: 'Corpo parado e começo e fim parecidos.',
    olheAPrevia: ' Olhe a prévia: a mão na frente do rosto só se vê tocando.',
    licencaFbx: 'Mixamo (termos da Adobe); não redistribuir',
    licencaVrma: 'conferir a licença do arquivo enviado',
  },
  // Painel do operador. O público nunca vê nada daqui.
  diagnostico: {
    versao: 'Versão',
    emPe: 'Em pé há',
    fps: 'Quadros por segundo',
    medindo: 'medindo',
    imagem: 'Imagem',
    imagemPerdida: 'contexto perdido',
    imagemOk: 'normal',
    memoria: 'Memória',
    memoriaValor: (usada, limite) => `${usada} MB de ${limite} MB`,
    semMemoria: 'o navegador não informa',
    gpu: 'Na placa de vídeo',
    gpuValor: (g, t) => `${g} geometrias, ${t} texturas`,
    semDados: 'sem dados',
    respostaGemini: 'Resposta do Gemini',
    ateFala: 'Até a primeira fala',
    semMedida: 'sem medida ainda',
    ms: (v, n) => (n ? `${v} ms (mediana de ${n})` : `${v} ms`),
    respostasHoje: 'Respostas hoje',
    respostasValor: (dia, sessao) => `${dia} (${sessao} nesta sessão)`,
    tokensHoje: 'Tokens hoje',
    tokensValor: (entrada, saida) => `${entrada} de entrada, ${saida} de saída`,
    gastoHoje: 'Gasto hoje',
    gastoValor: (reais, usd) => `R$ ${reais} (US$ ${usd})`,
    gastoSemPreco: (usd, modelos) => `US$ ${usd}, sem preço para ${modelos}`,
    recargas: 'Recargas automáticas',
    erros: 'Erros',
    semErros: 'nenhum',
    errosValor: (n, hora) => `${n}, último às ${hora}`,
    fonte: (fonte) => `Preços: ${fonte}. Sem preço do modelo na tabela, o gasto aparece só em tokens.`,
    semPerdaDeContexto: 'Este navegador não deixa derrubar o contexto de propósito (falta WEBGL_lose_context).',
    servicos: {
      gemini: (modelo) => `chave configurada, modelo ${modelo}`,
      semChave: 'sem chave',
      servidorOk: ' (servidor respondendo)',
      servidorRuim: (detalhe) => ` (servidor ${detalhe})`,
      escolhendo: 'escolhendo',
      ouvindo: 'ouvindo agora',
      ouvidoPronto: 'pronto',
      camLigada: 'ligada',
      camDesligada: 'desligada',
      avatar: (nome, licenca) => `${nome} carregado${licenca ? `, licença ${licenca}` : ''}`,
      semAvatar: 'sem avatar',
    },
  },
};
